apiVersion: v1
kind: Service
metadata:
  name: tomcatservice
  labels:
    app: tomcat
spec:
  ports:
    - port: 88
      name: tomcatapp
  clusterIP: None
  selector:
      app: tomcat

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tomcatapp
spec:
  serviceName: tomcatservice
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcatcontainer
          image: tomcat:latest
          ports:
            - containerPort: 88
              name: tomcatservice
          volumeMounts:
            - name: www
              mountPath: /usr/share/tomcat/html
  volumes:
    - name: www
  restartPolicy: Never
