apiVersion: v1
kind: ServiceAccount
metadata:
  name: sampleaccount
  namespace: svc-mngt
---
apiVersion: v1
kind: Secret
metadata:
  name: samplesecret
  namespace: svc-mngt
  annotations:
    kubernetes.io/service-account.name: sampleaccount
type: kubernetes.io/service-account-token
