apiVersion: v1
kind: Pod
metadata:
  name: copy-demo
  labels: 
     app: ubuntu
     env: test
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command:
        - "sleep"
        - "3600"
      imagePullPolicy: IfNotPresent
 

