apiVersion: v1
kind: Pod
metadata:
  name: labelexample
  labels:
    env: development
    owner: shreyash
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 9000
  
