apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
      app: mysql
data:
  master.cnf: |
    [mysqld]
    log-bin
  slave.cnf: |

    [mysqld]
    super-read-only
---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports: 
    - name: mysql
      port: 3306
  clusterIP: None
  selector: 
    app: mysql
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  labels:
    app: mysql
spec:
  ports:
    - name: mysql
      port: 3306
  selector:
    app: mysql
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: init-mysql
          image: mysql:5.7 
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "qwerty@123" 
