apiVersion: v1
kind: Pod
metadata:
  name: podv13
spec:
    volumes:
      - name: shared-data
        emptyDir: {}
    containers:
      - name: containerv13
        image: nginx
        volumeMounts:
          - name: shared-data
            mountPath: /usr/share/nginx/html
    hostNetwork: true
    dnsPolicy: Default
