apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: container-with-volume
      image: k8s.gcr.io/busybox
      command: ["/bin/sh", "-c", "ls /etc/config/"]
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: config-for-volume
  restartPolicy: Never
      
  
