apiVersion: v1
kind: Pod
metadata:
  name: userinterfacelayer
spec:
  containers:
    - name: app
      image: nginx
      resources:
        requests:
          memory: "2Gi"
            #0.5 milicpu allocating
          cpu: "500m"
        limits:
          memory: "3Gi"
          cpu: "1000m"

