apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxappdeployment
  labels:
    app: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
         - name: nginx
           image: nginx:1.14.2
           ports:
             - containerPort: 90
