apiVersion: v1
kind: Service
metadata:
  name: mynodeport
spec:
  type: NodePort
  selector:
    app: MyAppService
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007

---
apiVersion: v1
kind: Service
metadata:
  name: mynodeportlb
spec:
  selector: 
    app: MyAppServices
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  type: LoadBalancer
