apiVersion: v1
kind: Pod
metadata:
  name: pod-using-secret-env
spec:
  containers:
    - name: dbcontainer
      image: mysql
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
  restartPolicy: Never
