apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: podv179
spec:
  containers:
    - name: containerv179
      image: k8s.gcr.io/busybox
      args:
        - /bin/sh
        - -c 
        - touch /tmp/healthy;sleep 50; rm -f /tmp/healthy; sleep 600;
      livenessProbe: 
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 10
        periodSeconds: 10


