apiVersion: v1
kind: Pod
metadata:
  name: samplepodv6
spec:
  containers:
    - name: containersv6
      image: k8s.gcr.io/busybox
      command: ["/bin/sh", "-c", "env" ] 
      env:
        - name: ENV_KEY1
          valueFrom:
            configMapKeyRef:
              name: env-config3
              key: key1.data
        - name: ENV_KEY2
          valueFrom:
            configMapKeyRef:
              name: env-config4
              key: log.level
  restartPolicy: Never
