apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-example
  labels:
    type: local
spec:
  storageClassName: manual
  capacity: 
    storage: 10Gi
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdeployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: testnginx
          volumeMounts:
            - mountPath: /app/folder
              name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: volume-claim

