apiVersion: v1
kind: Pod
metadata:
  name: aws-ebs
spec:
  containers:
    - image: k8s.gcr.io/test-webserver
      name: test-container
      volumeMounts:
        - mountPath: /aws-ebs
          name: test-volume
  volumes:
    - name: test-volume
      awsElasticBlockStore:
        volumeID: "volumeid"
        fsType: ext4
