apiVersion: v1
kind: Pod
metadata:
  name: podv7
spec:
  containers:
    - name: containerv7
      image: busybox
      args:
        - /bin/sh
        - -c
        - >
          i=0;
          while true;
          do
            echo "$: $(date)" >> /var/log/log1.log;
            echo "$(date) INFO $i" >> /var/log/log2.log;
            i=$((i+1));
            sleep 2;
          done;
      volumeMounts:
        - name: varlog
          mountPath: /var/log
    - name: log1 
      image: busybox
      args: [/bin/sh, -c , 'tail -n+1 -f  /var/log/log1.log']
      volumeMounts:
        - name: varlog
          mountPath: /var/log
    - name: log2
      image: busybox
      args: [/bin/sh, -c, 'tail -f /var/log/log2.log']
      volumeMounts:
        - name: varlog
          mountPath: /var/log
  volumes:
    - name: varlog
      emptyDir: {}
