apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: nginxserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxserver
  template:
    metadata:
      labels:
        app: nginxserver
    spec:
      containers:
        - name: nginxcontainer
          image: nginx:1.14.2
          ports:
            - containerPort: 80


