apiVersion: v1
kind: Pod
metadata:
  name: initsample
spec:
  containers:
    - name: webcontainer
      image: nginx
      ports:
        - containerPort: 90
      volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html

  initContainers:
    - name: install
      image: busybox
      command:
        - wget
        - "-O"
        - "/work-dir/index.html"
        - http://info.cern.ch
      volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
  dnsPolicy: Default
  volumes: 
    - name: workdir
      emptyDir: {}
