apiVersion: v1
kind: Pod
metadata:
  name: secrettestpod
spec:
  containers:
    - name: secretpod
      image: redis
      env:
        - name: APP_USERNAME
          valueFrom:
            secretKeyRef:
              name: appusersecret
              key: username
      volumeMounts:
        - name: tmp
          mountPath: "/admincred/"
          readOnly: true
  volumes:
    - name: tmp
      secret:
        secretName: appusersecret
