apiVersion: v1
kind: Pod
metadata:
  name: podsampleforsecret
spec:
  containers:
    - name: mycontainer
      image: mysql
      volumeMounts:
        - name: data
          mountPath: "/etc/data"
          readOnly: true
  volumes:
    - name: data
      secret:
        secretName: mysecret
      
